"""add filename

Revision ID: cfdbd0889829
Revises: 91967ee02dc6
Create Date: 2022-11-25 14:50:42.242325

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cfdbd0889829"
down_revision = "91967ee02dc6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "artifact",
        sa.Column("filename", sa.String(length=70)),
        schema="wefusion",
    )
    op.execute("UPDATE wefusion.artifact SET filename = id || '.jpg' ")
    op.alter_column("artifact", "filename", nullable=False, schema="wefusion")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("artifact", "filename", schema="wefusion")
    # ### end Alembic commands ###
