"""feature/user-likes

Revision ID: 78deb2019b8b
Revises: cfdbd0889829
Create Date: 2022-12-11 15:00:46.234958

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "78deb2019b8b"
down_revision = "cfdbd0889829"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_artifact",
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("artifact_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["wefusion.artifact.id"],
            name=op.f("fk__user_artifact__artifact__artifact_id"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["wefusion.user.id"],
            name=op.f("fk__user_artifact__user__user_id"),
        ),
        sa.PrimaryKeyConstraint(
            "user_id",
            "artifact_id",
            name=op.f("pk__user_artifact__user_id_artifact_id"),
        ),
        schema="wefusion",
    )
    op.create_index(
        "ix__user_id_artifact_id_type",
        "user_artifact",
        ["user_id", "artifact_id", "type"],
        unique=False,
        schema="wefusion",
    )
    op.create_index(
        "ix__user_id_type",
        "user_artifact",
        ["user_id", "type"],
        unique=False,
        schema="wefusion",
    )
    op.drop_constraint(
        "fk__artifact__user__user_id", "artifact", schema="wefusion", type_="foreignkey"
    )
    op.drop_column("artifact", "user_id", schema="wefusion")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "artifact",
        sa.Column("user_id", postgresql.UUID(), autoincrement=False, nullable=False),
        schema="wefusion",
    )
    op.create_foreign_key(
        "fk__artifact__user__user_id",
        "artifact",
        "user",
        ["user_id"],
        ["id"],
        source_schema="wefusion",
        referent_schema="wefusion",
    )
    op.drop_index("ix__user_id_type", table_name="user_artifact", schema="wefusion")
    op.drop_index(
        "ix__user_id_artifact_id_type", table_name="user_artifact", schema="wefusion"
    )
    op.drop_table("user_artifact", schema="wefusion")
    # ### end Alembic commands ###
