"""add user_artifact_comment table

Revision ID: d5443c6592b9
Revises: 78deb2019b8b
Create Date: 2022-12-21 01:32:25.034879

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d5443c6592b9"
down_revision = "78deb2019b8b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_artifact_comment",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("artifact_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("comment", sa.String(length=1024), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["wefusion.artifact.id"],
            name=op.f("fk__user_artifact_comment__artifact__artifact_id"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["wefusion.user.id"],
            name=op.f("fk__user_artifact_comment__user__user_id"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__user_artifact_comment__id")),
        schema="wefusion",
    )
    op.create_index(
        op.f("ix__artifact_id"),
        "user_artifact_comment",
        ["artifact_id"],
        unique=False,
        schema="wefusion",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix__artifact_id"), table_name="user_artifact_comment", schema="wefusion"
    )
    op.drop_table("user_artifact_comment", schema="wefusion")
    # ### end Alembic commands ###
